# Project 3: Data Cleaning - Tidy up messy Datasets (Movies Dataset)

# Project Brief for Self-Coders

Here you´ll have the opportunity to code major parts of Project 3 on your own. If you need any help or inspiration, have a look at the Videos or the Jupyter Notebook with the full code. <br> <br>
Keep in mind that it´s all about __getting the right results/conclusions__. It´s not about finding the identical code. Things can be coded in many different ways. Even if you come to the same conclusions, it´s very unlikely that we have the very same code.

## First Steps

1. __Load__ and __inspect__ the messy dataset __movies_metadata.csv__. Identify columns with nested / stringified json data.

In [810]:
from IPython.display import HTML
import pandas as pd
movies = pd.read_csv("movies_metadata.csv",low_memory=False)
pd.options.display.max_columns = 30
pd.options.display.max_colwidth = 200
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45466 entries, 0 to 45465
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   adult                  45466 non-null  object
 1   belongs_to_collection  4494 non-null   object
 2   budget                 45466 non-null  object
 3   genres                 45466 non-null  object
 4   homepage               7782 non-null   object
 5   id                     45466 non-null  object
 6   imdb_id                45449 non-null  object
 7   original_language      45455 non-null  object
 8   original_title         45466 non-null  object
 9   overview               44512 non-null  object
 10  popularity             45461 non-null  object
 11  poster_path            45080 non-null  object
 12  production_companies   45463 non-null  object
 13  production_countries   45463 non-null  object
 14  release_date           45379 non-null  object
 15  revenue                45460 non-null  float64
 16  runtime                45203 non-null  float64
 17  spoken_languages       45460 non-null  object
 18  status                 45379 non-null  object
 19  tagline                20412 non-null  object
 20  title                  45460 non-null  object
 21  video                  45460 non-null  object
 22  vote_average           45460 non-null  float64
 23  vote_count             45460 non-null  float64
dtypes: float64(4), object(20)
memory usage: 8.3+ MB

In [811]:

movies.genres.to_frame()

                                                                                                  genres
0       [{'id': 16, 'name': 'Animation'}, {'id': 35, 'name': 'Comedy'}, {'id': 10751, 'name': 'Family'}]
1      [{'id': 12, 'name': 'Adventure'}, {'id': 14, 'name': 'Fantasy'}, {'id': 10751, 'name': 'Family'}]
2                                       [{'id': 10749, 'name': 'Romance'}, {'id': 35, 'name': 'Comedy'}]
3          [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'name': 'Drama'}, {'id': 10749, 'name': 'Romance'}]
4                                                                         [{'id': 35, 'name': 'Comedy'}]
...                                                                                                  ...
45461                                     [{'id': 18, 'name': 'Drama'}, {'id': 10751, 'name': 'Family'}]
45462                                                                      [{'id': 18, 'name': 'Drama'}]
45463        [{'id': 28, 'name': 'Action'}, {'id': 18, 'name': 'Drama'}, {'id': 53, 'name': 'Thriller'}]
45464                                                                                                 []
45465                                                                                                 []

[45466 rows x 1 columns]

## Dropping irrelevant Columns

2. __Drop__ the irrelevant columns 'adult', 'imdb_id', 'original_title', 'video' and 'homepage'.

In [812]:
movies.adult.value_counts()

adult
False                                                                                                                             45454
True                                                                                                                                  9
 - Written by Ørnås                                                                                                                   1
 Rune Balot goes to a casino connected to the October corporation to try to wrap up her case once and for all.                        1
 Avalanche Sharks tells the story of a bikini contest that turns into a horrifying affair when it is hit by a shark avalanche.        1
Name: count, dtype: int64

In [813]:
movies.head(10)

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,popularity,poster_path,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', 'poster_path': '/7G9915LfUQ2lVfwMEEhDsn3kT4B.jpg', 'backdrop_path': '/9FBwqcd9IRruEDUrTdcaafOMKUq.jpg'}",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, 'name': 'Comedy'}, {'id': 10751, 'name': 'Family'}]",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his room until Andy's birthday brings Buzz Lightyear onto the scene. Afraid of losing his place in Andy's heart, Woody plots against Buzz. But when circum...",21.946943,/rhIRbceoE9lR4veEXuwCC2wARtG.jpg,"[{'name': 'Pixar Animation Studios', 'id': 3}]","[{'iso_3166_1': 'US', 'name': 'United States of America'}]",1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, 'name': 'Fantasy'}, {'id': 10751, 'name': 'Family'}]",NaN,8844,tt0113497,en,Jumanji,"When siblings Judy and Peter discover an enchanted board game that opens the door to a magical world, they unwittingly invite Alan -- an adult who's been trapped inside the game for 26 years -- in...",17.015539,/vzmL6fP7aPKNKPRTFnZmiUfciyV.jpg,"[{'name': 'TriStar Pictures', 'id': 559}, {'name': 'Teitler Film', 'id': 2550}, {'name': 'Interscope Communications', 'id': 10201}]","[{'iso_3166_1': 'US', 'name': 'United States of America'}]",1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso_639_1': 'fr', 'name': 'Français'}]",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collection', 'poster_path': '/nLvUdqgPgm3F85NMCii9gVFUcet.jpg', 'backdrop_path': '/hypTnLot2z8wpFS7qwsQHW1uV8u.jpg'}",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, 'name': 'Comedy'}]",NaN,15602,tt0113228,en,Grumpier Old Men,"A family wedding reignites the ancient feud between next-door neighbors and fishing buddies John and Max. Meanwhile, a sultry Italian divorcée opens a restaurant at the local bait shop, alarming t...",11.7129,/6ksm1sjKMFLbO7UY2i6G1ju9SML.jpg,"[{'name': 'Warner Bros.', 'id': 6194}, {'name': 'Lancaster Gate', 'id': 19464}]","[{'iso_3166_1': 'US', 'name': 'United States of America'}]",1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for Love.,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'name': 'Drama'}, {'id': 10749, 'name': 'Romance'}]",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the women are holding their breath, waiting for the elusive ""good man"" to break a string of less-than-stellar lovers. Friends and confidants Vannah, Bernie, ...",3.859495,/16XOMpEaLWkrcPqSQqhTmeJuqQl.jpg,"[{'name': 'Twentieth Century Fox Film Corporation', 'id': 306}]","[{'iso_3166_1': 'US', 'name': 'United States of America'}]",1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself... and never let you forget it.,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Collection', 'poster_path': '/nts4iOmNnq7GNicycMJ9pSAn204.jpg', 'backdrop_path': '/7qwE57OVZmMJChBpLEbJEmzUydk.jpg'}",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,"Just when George Banks has recovered from his daughter's wedding, he receives the news that she's pregnant ... and that George's wife, Nina, is expecting too. He was planning on selling their home...",8.387519,/e64sOI48hQXyru7naBFyssKFxVd.jpg,"[{'name': 'Sandollar Productions', 'id': 5842}, {'name': 'Touchstone Pictures', 'id': 9195}]","[{'iso_3166_1': 'US', 'name': 'United States of America'}]",1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's In For The Surprise Of His Life!,Father of the Bride Part II,False,5.7,173.0
5,False,NaN,60000000,"[{'id': 28, 'name': 'Action'}, {'id': 80, 'name': 'Crime'}, {'id': 18, 'name': 'Drama'}, {'id': 53, 'name': 'Thriller'}]",NaN,949,tt0113277,en,Heat,"Obsessive master thief, Neil McCauley leads a top-notch crew on various insane heists throughout Los Angeles while a mentally unstable detective, Vincent Hanna pursues him without rest. Each man r...",17.924927,/zMyfPUelumio3tiDKPffaUpsQTD.jpg,"[{'name': 'Regency Enterprises', 'id': 508}, {'name': 'Forward Pass', 'id': 675}, {'name': 'Warner Bros.', 'id': 6194}]","[{'iso_3166_1': 'US', 'name': 'United States of America'}]",1995-12-15,187436818.0,170.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso_639_1': 'es', 'name': 'Español'}]",Released,A Los Angeles Crime Saga,Heat,False,7.7,1886.0
6,False,NaN,58000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 10749, 'name': 'Romance'}]",NaN,11860,tt0114319,en,Sabrina,"An ugly duckling having undergone a remarkable change, still harbors feelings for her crush: a carefree playboy, but not before his business-focused brother has something to say about it.",6.677277,/jQh15y5YB7bWz1NtffNZmRw0s9D.jpg,"[{'name': 'Paramount Pictures', 'id': 4}, {'name': 'Scott Rudin Productions', 'id': 258}, {'name': 'Mirage Enterprises', 'id': 932}, {'name': 'Sandollar Productions', 'id': 5842}, {'name': 'Conste...","[{'iso_3166_1': 'DE', 'name': 'Germany'}, {'iso_3166_1': 'US', 'name': 'United States of America'}]",1995-12-15,0.0,127.0,"[{'iso_639_1': 'fr', 'name': 'Français'}, {'iso_639_1': 'en', 'name': 'English'}]",Released,You are cordially invited to the most surprising merger of the year.,Sabrina,False,6.2,141.0
7,False,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'name': 'Adventure'}, {'id': 18, 'name': 'Drama'}, {'id': 10751, 'name': 'Family'}]",NaN,45325,tt0112302,en,Tom and Huck,"A mischievous young boy, Tom Sawyer, witnesses a murder by the deadly Injun Joe. Tom becomes friends with Huckleberry Finn, a boy with no future and no family. Tom has to choose between honoring a...",2.561161,/sGO5Qa55p7wTu7FJcX4H4xIVKvS.jpg,"[{'name': 'Walt Disney Pictures', 'id': 2}]","[{'iso_3166_1': 'US', 'name': 'United States of America'}]",1995-12-22,0.0,97.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso_639_1': 'de', 'name': 'Deutsch'}]",Released,The Original Bad Boys.,Tom and Huck,False,5.4,45.0
8,False,NaN,35000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'name': 'Adventure'}, {'id': 53, 'name': 'Thriller'}]",NaN,9091,tt0114576,en,Sudden Death,"International action superstar Jean Claude Van Damme teams with Powers Boothe in a Tension-packed, suspense thriller, set against the back-drop of a Stanley Cup game.Van Damme portrays a father wh...",5.23158,/eoWvKD60lT95Ss1MYNgVExpo5iU.jpg,"[{'name': 'Universal Pictures', 'id': 33}, {'name': 'Imperial Entertainment', 'id': 21437}, {'name': 'Signature Entertainment', 'id': 23770}]","[{'iso_3166_1': 'US', 'name': 'United States of America'}]",1995-12-22,64350171.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Terror goes into overtime.,Sudden Death,False,5.5,174.0
9,False,"{'id': 645, 'name': 'James Bond Collection', 'poster_path': '/HORpg5CSkmeQlAolx3bKMrKgfi.jpg', 'backdrop_path': '/6VcVl48kNKvdXOZfJPdarlUGOsk.jpg'}",58000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, 'name': 'Action'}, {'id': 53, 'name': 'Thriller'}]",http://www.mgm.com/view/movie/757/Goldeneye/,710,tt0113189,en,GoldenEye,James Bond must unmask the mysterious head of the Janus Syndicate and prevent the leader from utilizing the GoldenEye weapons system to inflict devastating revenge on Britain.,14.686036,/5c0ovjT41KnYIHYuF4AWsTe3sKh.jpg,"[{'name': 'United Artists', 'id': 60}, {'name': 'Eon Productions', 'id': 7576}]","[{'iso_3166_1': 'GB', 'name': 'United Kingdom'}, {'iso_3166_1': 'US', 'name': 'United States of America'}]",1995-11-16,352194034.0,130.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso_639_1': 'ru', 'name': 'Pусский'}, {'iso_639_1': 'es', 'name': 'Español'}]",Released,No limits. No fears. No substitutes.,GoldenEye,False,6.6,1194.0

In [814]:
movies.drop(columns = ["adult"] , inplace = True)
movies.drop(columns = ['imdb_id'] ,inplace = True)
movies.drop(columns = ['original_title'],inplace = True)
movies.drop(columns = ['video'],inplace = True)
movies.drop(columns = ['homepage'] ,inplace = True)

In [815]:
"adult" in movies.columns

False

In [816]:
movies.head(10)

,belongs_to_collection,budget,genres,id,original_language,overview,popularity,poster_path,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,"{'id': 10194, 'name': 'Toy Story Collection', 'poster_path': '/7G9915LfUQ2lVfwMEEhDsn3kT4B.jpg', 'backdrop_path': '/9FBwqcd9IRruEDUrTdcaafOMKUq.jpg'}",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, 'name': 'Comedy'}, {'id': 10751, 'name': 'Family'}]",862,en,"Led by Woody, Andy's toys live happily in his room until Andy's birthday brings Buzz Lightyear onto the scene. Afraid of losing his place in Andy's heart, Woody plots against Buzz. But when circum...",21.946943,/rhIRbceoE9lR4veEXuwCC2wARtG.jpg,"[{'name': 'Pixar Animation Studios', 'id': 3}]","[{'iso_3166_1': 'US', 'name': 'United States of America'}]",1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,7.7,5415.0
1,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, 'name': 'Fantasy'}, {'id': 10751, 'name': 'Family'}]",8844,en,"When siblings Judy and Peter discover an enchanted board game that opens the door to a magical world, they unwittingly invite Alan -- an adult who's been trapped inside the game for 26 years -- in...",17.015539,/vzmL6fP7aPKNKPRTFnZmiUfciyV.jpg,"[{'name': 'TriStar Pictures', 'id': 559}, {'name': 'Teitler Film', 'id': 2550}, {'name': 'Interscope Communications', 'id': 10201}]","[{'iso_3166_1': 'US', 'name': 'United States of America'}]",1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso_639_1': 'fr', 'name': 'Français'}]",Released,Roll the dice and unleash the excitement!,Jumanji,6.9,2413.0
2,"{'id': 119050, 'name': 'Grumpy Old Men Collection', 'poster_path': '/nLvUdqgPgm3F85NMCii9gVFUcet.jpg', 'backdrop_path': '/hypTnLot2z8wpFS7qwsQHW1uV8u.jpg'}",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, 'name': 'Comedy'}]",15602,en,"A family wedding reignites the ancient feud between next-door neighbors and fishing buddies John and Max. Meanwhile, a sultry Italian divorcée opens a restaurant at the local bait shop, alarming t...",11.7129,/6ksm1sjKMFLbO7UY2i6G1ju9SML.jpg,"[{'name': 'Warner Bros.', 'id': 6194}, {'name': 'Lancaster Gate', 'id': 19464}]","[{'iso_3166_1': 'US', 'name': 'United States of America'}]",1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for Love.,Grumpier Old Men,6.5,92.0
3,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'name': 'Drama'}, {'id': 10749, 'name': 'Romance'}]",31357,en,"Cheated on, mistreated and stepped on, the women are holding their breath, waiting for the elusive ""good man"" to break a string of less-than-stellar lovers. Friends and confidants Vannah, Bernie, ...",3.859495,/16XOMpEaLWkrcPqSQqhTmeJuqQl.jpg,"[{'name': 'Twentieth Century Fox Film Corporation', 'id': 306}]","[{'iso_3166_1': 'US', 'name': 'United States of America'}]",1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself... and never let you forget it.,Waiting to Exhale,6.1,34.0
4,"{'id': 96871, 'name': 'Father of the Bride Collection', 'poster_path': '/nts4iOmNnq7GNicycMJ9pSAn204.jpg', 'backdrop_path': '/7qwE57OVZmMJChBpLEbJEmzUydk.jpg'}",0,"[{'id': 35, 'name': 'Comedy'}]",11862,en,"Just when George Banks has recovered from his daughter's wedding, he receives the news that she's pregnant ... and that George's wife, Nina, is expecting too. He was planning on selling their home...",8.387519,/e64sOI48hQXyru7naBFyssKFxVd.jpg,"[{'name': 'Sandollar Productions', 'id': 5842}, {'name': 'Touchstone Pictures', 'id': 9195}]","[{'iso_3166_1': 'US', 'name': 'United States of America'}]",1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's In For The Surprise Of His Life!,Father of the Bride Part II,5.7,173.0
5,NaN,60000000,"[{'id': 28, 'name': 'Action'}, {'id': 80, 'name': 'Crime'}, {'id': 18, 'name': 'Drama'}, {'id': 53, 'name': 'Thriller'}]",949,en,"Obsessive master thief, Neil McCauley leads a top-notch crew on various insane heists throughout Los Angeles while a mentally unstable detective, Vincent Hanna pursues him without rest. Each man r...",17.924927,/zMyfPUelumio3tiDKPffaUpsQTD.jpg,"[{'name': 'Regency Enterprises', 'id': 508}, {'name': 'Forward Pass', 'id': 675}, {'name': 'Warner Bros.', 'id': 6194}]","[{'iso_3166_1': 'US', 'name': 'United States of America'}]",1995-12-15,187436818.0,170.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso_639_1': 'es', 'name': 'Español'}]",Released,A Los Angeles Crime Saga,Heat,7.7,1886.0
6,NaN,58000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 10749, 'name': 'Romance'}]",11860,en,"An ugly duckling having undergone a remarkable change, still harbors feelings for her crush: a carefree playboy, but not before his business-focused brother has something to say about it.",6.677277,/jQh15y5YB7bWz1NtffNZmRw0s9D.jpg,"[{'name': 'Paramount Pictures', 'id': 4}, {'name': 'Scott Rudin Productions', 'id': 258}, {'name': 'Mirage Enterprises', 'id': 932}, {'name': 'Sandollar Productions', 'id': 5842}, {'name': 'Conste...","[{'iso_3166_1': 'DE', 'name': 'Germany'}, {'iso_3166_1': 'US', 'name': 'United States of America'}]",1995-12-15,0.0,127.0,"[{'iso_639_1': 'fr', 'name': 'Français'}, {'iso_639_1': 'en', 'name': 'English'}]",Released,You are cordially invited to the most surprising merger of the year.,Sabrina,6.2,141.0
7,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'name': 'Adventure'}, {'id': 18, 'name': 'Drama'}, {'id': 10751, 'name': 'Family'}]",45325,en,"A mischievous young boy, Tom Sawyer, witnesses a murder by the deadly Injun Joe. Tom becomes friends with Huckleberry Finn, a boy with no future and no family. Tom has to choose between honoring a...",2.561161,/sGO5Qa55p7wTu7FJcX4H4xIVKvS.jpg,"[{'name': 'Walt Disney Pictures', 'id': 2}]","[{'iso_3166_1': 'US', 'name': 'United States of America'}]",1995-12-22,0.0,97.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso_639_1': 'de', 'name': 'Deutsch'}]",Released,The Original Bad Boys.,Tom and Huck,5.4,45.0
8,NaN,35000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'name': 'Adventure'}, {'id': 53, 'name': 'Thriller'}]",9091,en,"International action superstar Jean Claude Van Damme teams with Powers Boothe in a Tension-packed, suspense thriller, set against the back-drop of a Stanley Cup game.Van Damme portrays a father wh...",5.23158,/eoWvKD60lT95Ss1MYNgVExpo5iU.jpg,"[{'name': 'Universal Pictures', 'id': 33}, {'name': 'Imperial Entertainment', 'id': 21437}, {'name': 'Signature Entertainment', 'id': 23770}]","[{'iso_3166_1': 'US', 'name': 'United States of America'}]",1995-12-22,64350171.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Terror goes into overtime.,Sudden Death,5.5,174.0
9,"{'id': 645, 'name': 'James Bond Collection', 'poster_path': '/HORpg5CSkmeQlAolx3bKMrKgfi.jpg', 'backdrop_path': '/6VcVl48kNKvdXOZfJPdarlUGOsk.jpg'}",58000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, 'name': 'Action'}, {'id': 53, 'name': 'Thriller'}]",710,en,James Bond must unmask the mysterious head of the Janus Syndicate and prevent the leader from utilizing the GoldenEye weapons system to inflict devastating revenge on Britain.,14.686036,/5c0ovjT41KnYIHYuF4AWsTe3sKh.jpg,"[{'name': 'United Artists', 'id': 60}, {'name': 'Eon Productions', 'id': 7576}]","[{'iso_3166_1': 'GB', 'name': 'United Kingdom'}, {'iso_3166_1': 'US', 'name': 'United States of America'}]",1995-11-16,352194034.0,130.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso_639_1': 'ru', 'name': 'Pусский'}, {'iso_639_1': 'es', 'name': 'Español'}]",Released,No limits. No fears. No substitutes.,GoldenEye,6.6,1194.0

## How to handle stringified JSON columns

3. __Evaluate__ Python Expressions in the stringified columns ["belongs_to_collection", "genres", "production_countries", "production_companies", "spoken_languages"] and __remove quotes__ ("") where possible.

In [817]:
import json
import ast
json2  = '{"id": 4, "name" : "Dog"}'
json.loads(json2)   #keys should be enclosed withing double quotes in json2

movies.genres.apply(lambda x : json.loads(x.replace("'",'"')))

0         [{'id': 16, 'name': 'Animation'}, {'id': 35, 'name': 'Comedy'}, {'id': 10751, 'name': 'Family'}]
1        [{'id': 12, 'name': 'Adventure'}, {'id': 14, 'name': 'Fantasy'}, {'id': 10751, 'name': 'Family'}]
2                                         [{'id': 10749, 'name': 'Romance'}, {'id': 35, 'name': 'Comedy'}]
3            [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'name': 'Drama'}, {'id': 10749, 'name': 'Romance'}]
4                                                                           [{'id': 35, 'name': 'Comedy'}]
                                                       ...
45461                                       [{'id': 18, 'name': 'Drama'}, {'id': 10751, 'name': 'Family'}]
45462                                                                        [{'id': 18, 'name': 'Drama'}]
45463          [{'id': 28, 'name': 'Action'}, {'id': 18, 'name': 'Drama'}, {'id': 53, 'name': 'Thriller'}]
45464                                                                                                   []
45465                                                                                                   []
Name: genres, Length: 45466, dtype: object

In [818]:
#or simply using ast
ast.literal_eval(json2)

{'id': 4, 'name': 'Dog'}

In [819]:
json_col = ["belongs_to_collection","genres","production_countries"
              ,"production_companies","spoken_languages"]
movies.loc[:,json_col]

,belongs_to_collection,genres,production_countries,production_companies,spoken_languages
0,"{'id': 10194, 'name': 'Toy Story Collection', 'poster_path': '/7G9915LfUQ2lVfwMEEhDsn3kT4B.jpg', 'backdrop_path': '/9FBwqcd9IRruEDUrTdcaafOMKUq.jpg'}","[{'id': 16, 'name': 'Animation'}, {'id': 35, 'name': 'Comedy'}, {'id': 10751, 'name': 'Family'}]","[{'iso_3166_1': 'US', 'name': 'United States of America'}]","[{'name': 'Pixar Animation Studios', 'id': 3}]","[{'iso_639_1': 'en', 'name': 'English'}]"
1,NaN,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, 'name': 'Fantasy'}, {'id': 10751, 'name': 'Family'}]","[{'iso_3166_1': 'US', 'name': 'United States of America'}]","[{'name': 'TriStar Pictures', 'id': 559}, {'name': 'Teitler Film', 'id': 2550}, {'name': 'Interscope Communications', 'id': 10201}]","[{'iso_639_1': 'en', 'name': 'English'}, {'iso_639_1': 'fr', 'name': 'Français'}]"
2,"{'id': 119050, 'name': 'Grumpy Old Men Collection', 'poster_path': '/nLvUdqgPgm3F85NMCii9gVFUcet.jpg', 'backdrop_path': '/hypTnLot2z8wpFS7qwsQHW1uV8u.jpg'}","[{'id': 10749, 'name': 'Romance'}, {'id': 35, 'name': 'Comedy'}]","[{'iso_3166_1': 'US', 'name': 'United States of America'}]","[{'name': 'Warner Bros.', 'id': 6194}, {'name': 'Lancaster Gate', 'id': 19464}]","[{'iso_639_1': 'en', 'name': 'English'}]"
3,NaN,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'name': 'Drama'}, {'id': 10749, 'name': 'Romance'}]","[{'iso_3166_1': 'US', 'name': 'United States of America'}]","[{'name': 'Twentieth Century Fox Film Corporation', 'id': 306}]","[{'iso_639_1': 'en', 'name': 'English'}]"
4,"{'id': 96871, 'name': 'Father of the Bride Collection', 'poster_path': '/nts4iOmNnq7GNicycMJ9pSAn204.jpg', 'backdrop_path': '/7qwE57OVZmMJChBpLEbJEmzUydk.jpg'}","[{'id': 35, 'name': 'Comedy'}]","[{'iso_3166_1': 'US', 'name': 'United States of America'}]","[{'name': 'Sandollar Productions', 'id': 5842}, {'name': 'Touchstone Pictures', 'id': 9195}]","[{'iso_639_1': 'en', 'name': 'English'}]"
...,...,...,...,...,...
45461,NaN,"[{'id': 18, 'name': 'Drama'}, {'id': 10751, 'name': 'Family'}]","[{'iso_3166_1': 'IR', 'name': 'Iran'}]",[],"[{'iso_639_1': 'fa', 'name': 'فارسی'}]"
45462,NaN,"[{'id': 18, 'name': 'Drama'}]","[{'iso_3166_1': 'PH', 'name': 'Philippines'}]","[{'name': 'Sine Olivia', 'id': 19653}]","[{'iso_639_1': 'tl', 'name': ''}]"
45463,NaN,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'name': 'Drama'}, {'id': 53, 'name': 'Thriller'}]","[{'iso_3166_1': 'US', 'name': 'United States of America'}]","[{'name': 'American World Pictures', 'id': 6165}]","[{'iso_639_1': 'en', 'name': 'English'}]"
45464,NaN,[],"[{'iso_3166_1': 'RU', 'name': 'Russia'}]","[{'name': 'Yermoliev', 'id': 88753}]",[]
45465,NaN,[],"[{'iso_3166_1': 'GB', 'name': 'United Kingdom'}]",[],"[{'iso_639_1': 'en', 'name': 'English'}]"

In [820]:
import numpy as np
movies.belongs_to_collection.apply(lambda x : isinstance(x,str))

0         True
1        False
2         True
3        False
4         True
         ...
45461    False
45462    False
45463    False
45464    False
45465    False
Name: belongs_to_collection, Length: 45466, dtype: bool

In [821]:
movies.belongs_to_collection = movies.belongs_to_collection.apply(lambda x : ast.literal_eval(x) if isinstance(x,str) else np.nan)

In [822]:
movies.genres = movies.genres.apply(lambda x : ast.literal_eval(x) if isinstance(x,str) else np.nan)
movies.production_companies = movies.production_companies.apply(lambda x : ast.literal_eval(x) if isinstance(x,str) else np.nan)
movies.production_countries = movies.production_countries.apply(lambda x : ast.literal_eval(x) if isinstance(x,str) else np.nan)
movies.spoken_languages = movies.spoken_languages.apply(lambda x : ast.literal_eval(x) if isinstance(x,str) else np.nan)

In [823]:
movies.genres[0]

[{'id': 16, 'name': 'Animation'},
 {'id': 35, 'name': 'Comedy'},
 {'id': 10751, 'name': 'Family'}]

In [824]:
movies.production_companies[0]

[{'name': 'Pixar Animation Studios', 'id': 3}]

## How to flatten nested Columns

4. __Extract__ only the __collection name__ from the column "belongs_to_collection" and __overwrite__ "belongs_to_collection". <br> For example: The value in the first row (Toy Story) should be 'Toy Story Collection'.

5. __Extract__ all __genre names__ from the column "genres" and __overwrite__ "genres". If a movie has more than one genre, __seperate genres by a pipe__ "|".<br>
For example: The value in the first row (Toy Story) should be 'Animation|Comedy|Family'.

6. __Extract__ all __spoken language names__ from the column "spoken_languages" and __overwrite__ "spoken_languages". If a movie has more than one spoken language, __seperate spoken languages by a pipe__ "|".<br>
For example: The value in the first row (Toy Story) should be 'English'.

7. __Extract__ all __production countries names__ from the column "production_countries" and __overwrite__ "production_countries". If a movie has more than one production country, __seperate production countries by a pipe__ "|".<br>
For example: The value in the first row (Toy Story) should be 'United States of America'.

8. __Extract__ all __production companies names__ from the column "production_companies" and __overwrite__ "production_companies". If a movie has more than one production company, __seperate production companies by a pipe__ "|".<br>
For example: The value in the first row (Toy Story) should be 'Pixar Animation Studios'

9. __Inspect__ all columns above with value_counts(). Do you see anything strange? __Take reasonable measures__!

In [825]:
movies.belongs_to_collection = movies.belongs_to_collection.apply(lambda x : x["name"] if isinstance(x,dict) else np.nan)

In [826]:
movies.belongs_to_collection

0                  Toy Story Collection
1                                   NaN
2             Grumpy Old Men Collection
3                                   NaN
4        Father of the Bride Collection
                      ...
45461                               NaN
45462                               NaN
45463                               NaN
45464                               NaN
45465                               NaN
Name: belongs_to_collection, Length: 45466, dtype: object

In [827]:
movies.belongs_to_collection.value_counts(dropna = True).head(10)

belongs_to_collection
The Bowery Boys                           29
Totò Collection                           27
James Bond Collection                     26
Zatôichi: The Blind Swordsman             26
The Carry On Collection                   25
Pokémon Collection                        22
Charlie Chan (Sidney Toler) Collection    21
Godzilla (Showa) Collection               16
Uuno Turhapuro                            15
Charlie Chan (Warner Oland) Collection    15
Name: count, dtype: int64

In [828]:
movies.genres = movies.genres.apply(lambda x : "|" .join(i['name'] for i in x))

In [829]:
movies["genres"] = movies["genres"].replace("",np.nan)

In [830]:
movies.genres

0         Animation|Comedy|Family
1        Adventure|Fantasy|Family
2                  Romance|Comedy
3            Comedy|Drama|Romance
4                          Comedy
                   ...
45461                Drama|Family
45462                       Drama
45463       Action|Drama|Thriller
45464                         NaN
45465                         NaN
Name: genres, Length: 45466, dtype: object

In [831]:
movies.spoken_languages = movies.spoken_languages.apply(lambda x : '|'.join(i['name'] for i in x )  if isinstance(x,list)else np.nan)

In [832]:
movies.spoken_languages.dropna()

0                 English
1        English|Français
2                 English
3                 English
4                 English
               ...
45461               فارسی
45462
45463             English
45464
45465             English
Name: spoken_languages, Length: 45460, dtype: object

In [833]:
movies.production_companies = movies.production_companies.apply(lambda x : '|'.join(i['name'] for i in x )  if isinstance(x,list)else np.nan)

In [834]:
movies.production_countries = movies.production_countries.apply(lambda x : '|'.join(i['name'] for i in x )  if isinstance(x,list)else np.nan)

In [835]:
movies.genres.value_counts()

genres
Drama                                      5000
Comedy                                     3621
Documentary                                2723
Drama|Romance                              1301
Comedy|Drama                               1135
                                           ...
TV Movie|Animation|Family|Comedy              1
Fantasy|Documentary|Animation|Drama           1
Fantasy|Mystery|Romance                       1
Animation|Action|Family|Science Fiction       1
Family|Animation|Romance|Comedy               1
Name: count, Length: 4068, dtype: int64

## Cleaning Numerical Columns

10. __Convert__ the datatype in the columns __"budget"__, __"id"__ and __"popularity"__ __to numeric__. Set invalid values as NaN.

11. __Analyze__ the columns __"budget"__ and __"revenue"__ and __"runtime"__. Analyze movies with a budget/revenue/runtime of 0. Do you think the value 0 is the most appropriate value? __Take reasonable measures__!

12. The columns "budget" and "revenue" shall show values in Million USD. __Convert and Overwrite__!

13. __Analyze__ movies with a __vote_count of 0__. What´s the __vote_average__ for those movies? Do you think this value is the most appropriate value? __Take reasonable measures__!

In [836]:
movies.budget  =  pd.to_numeric(movies.budget, errors = "coerce")

In [837]:
movies.budget = movies.budget.div(10000000)

In [838]:
movies["budget"] = movies["budget"].replace(0,np.nan)

In [839]:
df_budget = movies[["title","budget"]]
df_budget.set_index("title",inplace = True)

In [840]:
df_budget.sort_values(by = "budget" , ascending = False).head(10)

                                             budget
title
Pirates of the Caribbean: On Stranger Tides    38.0
Pirates of the Caribbean: At World's End       30.0
Avengers: Age of Ultron                        28.0
Superman Returns                               27.0
Transformers: The Last Knight                  26.0
Tangled                                        26.0
John Carter                                    26.0
Spider-Man 3                                   25.8
The Lone Ranger                                25.5
The Hobbit: The Desolation of Smaug            25.0

In [841]:
movies.revenue = pd.to_numeric(movies.revenue)
movies.revenue = movies.revenue.div(10000000)

In [842]:
movies.revenue = movies.revenue.replace(0,np.nan)

In [843]:
movies["runtime"] = movies["runtime"].replace(0,np.nan)

In [844]:
movies["id"] = pd.to_numeric(movies["id"], errors = "coerce")

In [845]:
movies['popularity'] = pd.to_numeric(movies["popularity"], errors = "coerce")

In [846]:
movies.loc[movies.vote_count == 0,"vote_average"] = np.nan

## Cleaning DateTime Columns

14. __Convert__ the datatype in the column __"release_date"__ __to datetime__. Set invalid values as NaN.

In [847]:
movies["release_date"] = pd.to_datetime(movies["release_date"],errors = "coerce")

## Cleaning Text / String Columns

15. __Analyze__ the text columns "overview" and "tagline". Try to identify __missing data that is not represented by NaN__ (e.g. "No Data"). __Replace as NaN__ (np.nan)!

In [848]:
movies.original_language.value_counts().head(50)

original_language
en    32269
fr     2438
it     1529
ja     1350
de     1080
es      994
ru      826
hi      508
ko      444
zh      409
sv      384
pt      316
cn      313
fi      297
nl      248
da      225
pl      219
tr      150
cs      130
el      113
no      106
fa      101
hu      100
ta       78
th       76
he       67
sr       63
ro       57
te       45
ar       39
ml       36
xx       33
bn       29
hr       29
mr       25
is       24
et       24
tl       23
id       20
lv       18
ka       18
sl       17
uk       16
bs       14
ca       12
ab       10
vi       10
bg       10
sk        9
lt        9
Name: count, dtype: int64

In [849]:
movies.overview.value_counts()

overview
No overview found.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       133
No Overview                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                7
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           5
No movie overview available.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               3
A few funny little novels about different aspects of life.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 3
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ...
"Of Time and The City" is both a love song and a eulogy to the director's birthplace of Liverpool, England. It is also a response to memory, reflection and the experience of losing a sense of place as the skyline changes and time takes it toll. The visual content of the film consists largely of archival clips of Liverpool from the 1940s to the 1960s, their nostalgic charm darkened by accompanying music and by the counterpoint of Davies’ dry, at times dyspeptic, voice-over narration. His voice thickens with emotion as he recalls the delights of juvenile movie-going or the ritual of a holiday trip to New Brighton, across the River Mersey, and hardens with contempt when he turns his gaze on the hoopla surrounding Queen Elizabeth’s coronation in 1953.      1
We are in the year 1871. A journalist for Versailles Television broadcasts a soothing and official view of events while a Commune television is set up to provide the perspectives of the Paris rebels. On a stage-like set, more than 200 actors interpret characters of the Commune, especially the Popincourt neighbourhood in the XIth arrondissement. They voice their own thoughts and feelings concerning the social and political reforms. The scenes consist mainly of long camera takes.                                                                                                                                                                                                                                                                                         1
A kindergarten director Troshkin is a dead ringer for a criminal nicknamed "Docent" who stole the priceless...                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             1
A man wakes up deep inside a cave. Suffering amnesia, he has no recollection of how he came to be here or of what happened to the man whose body he finds beside him. Tailed by a mysterious creature, he must continue through this strange and fantastic world. Enclosed, Tolbiac has no other option to reach the surface than to use REZO ZERO, secret observing cells in this cemetery-like abandoned mine.                                                                                                                                                                                                                                                                                                                                                                           1
50 years after decriminalisation of homosexuality in the UK, director Daisy Asquith mines the jewels of the BFI archive to take us into the relationships, desires, fears and expressions of gay men and women in the 20th century.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        1
Name: count, Length: 44307, dtype: int64

In [850]:
movies.tagline.value_counts()

tagline
Based on a true story.                                        7
Be careful what you wish for.                                 4
Trust no one.                                                 4
-                                                             4
Classic Albums                                                3
                                                             ..
A special force in a special kind of hell!                    1
Play it. Sing it. Shout it. Feel it.                          1
If It's On TV, It Must Be The Truth.                          1
"I LOVE YOU BABY, BUT MY WIFE JUST REFUSES TO UNDERSTAND!"    1
A deadly game of wits.                                        1
Name: count, Length: 20283, dtype: int64

In [851]:
movies["tagline"] = movies["tagline"].replace(to_replace='^-$', value=np.nan, regex=True)

In [852]:
movies.tagline.value_counts()

tagline
Based on a true story.                                        7
Trust no one.                                                 4
Be careful what you wish for.                                 4
Know Your Enemy                                               3
Who is John Galt?                                             3
                                                             ..
A special force in a special kind of hell!                    1
Play it. Sing it. Shout it. Feel it.                          1
If It's On TV, It Must Be The Truth.                          1
"I LOVE YOU BABY, BUT MY WIFE JUST REFUSES TO UNDERSTAND!"    1
A deadly game of wits.                                        1
Name: count, Length: 20282, dtype: int64

## Removing Duplicates

16. __Identify__ and __remove__ duplicates!

In [853]:
movies[movies.duplicated(keep = False)].sort_values(by = "id")

,belongs_to_collection,budget,genres,id,original_language,overview,popularity,poster_path,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
7345,NaN,NaN,Crime|Drama|Thriller,5511.0,fr,Hitman Jef Costello is a perfectionist who always carefully plans his murders and who never gets caught.,9.091288,/cvNW8IXigbaMNo4gKEIps0NGnhA.jpg,Fida cinematografica|Compagnie Industrielle et Commerciale Cinématographique (CICC)|TC Productions|Filmel,France|Italy,1967-10-25,0.003948,105.0,Français,Released,There is no solitude greater than that of the Samurai,Le Samouraï,7.9,187.0
9165,NaN,NaN,Crime|Drama|Thriller,5511.0,fr,Hitman Jef Costello is a perfectionist who always carefully plans his murders and who never gets caught.,9.091288,/cvNW8IXigbaMNo4gKEIps0NGnhA.jpg,Fida cinematografica|Compagnie Industrielle et Commerciale Cinématographique (CICC)|TC Productions|Filmel,France|Italy,1967-10-25,0.003948,105.0,Français,Released,There is no solitude greater than that of the Samurai,Le Samouraï,7.9,187.0
24844,NaN,NaN,Comedy|Drama,11115.0,en,"As an ex-gambler teaches a hot-shot college kid some things about playing cards, he finds himself pulled into the world series of poker, where his protégé is his toughest competition.",6.880365,/kHaBqrrozaG7rj6GJg3sUCiM29B.jpg,Andertainment Group|Crescent City Pictures|Tag Entertainment,United States of America,2008-01-29,NaN,85.0,English,Released,NaN,Deal,5.2,22.0
14012,NaN,NaN,Comedy|Drama,11115.0,en,"As an ex-gambler teaches a hot-shot college kid some things about playing cards, he finds himself pulled into the world series of poker, where his protégé is his toughest competition.",6.880365,/kHaBqrrozaG7rj6GJg3sUCiM29B.jpg,Andertainment Group|Crescent City Pictures|Tag Entertainment,United States of America,2008-01-29,NaN,85.0,English,Released,NaN,Deal,5.2,22.0
22151,NaN,NaN,Action|Horror|Science Fiction,18440.0,en,"When a comet strikes Earth and kicks up a cloud of toxic dust, hundreds of humans join the ranks of the living dead. But there's bad news for the survivors: The newly minted zombies are hell-bent ...",1.436085,/tWCyKXHuSrQdLAvNeeVJBnhf1Yv.jpg,,United States of America,2007-01-01,NaN,89.0,English,Released,NaN,Days of Darkness,5.0,5.0
14000,NaN,NaN,Action|Horror|Science Fiction,18440.0,en,"When a comet strikes Earth and kicks up a cloud of toxic dust, hundreds of humans join the ranks of the living dead. But there's bad news for the survivors: The newly minted zombies are hell-bent ...",1.436085,/tWCyKXHuSrQdLAvNeeVJBnhf1Yv.jpg,,United States of America,2007-01-01,NaN,89.0,English,Released,NaN,Days of Darkness,5.0,5.0
8068,NaN,NaN,Adventure|Animation|Drama|Action|Foreign,23305.0,en,"In feudal India, a warrior (Khan) who renounces his role as the longtime enforcer to a local lord becomes the prey in a murderous hunt through the Himalayan mountains.",1.967992,/9GlrmbZO7VGyqhaSR1utinRJz3L.jpg,Filmfour,France|Germany|India|United Kingdom,2001-09-23,NaN,86.0,हिन्दी,Released,NaN,The Warrior,6.3,15.0
9327,NaN,NaN,Adventure|Animation|Drama|Action|Foreign,23305.0,en,"In feudal India, a warrior (Khan) who renounces his role as the longtime enforcer to a local lord becomes the prey in a murderous hunt through the Himalayan mountains.",1.967992,/9GlrmbZO7VGyqhaSR1utinRJz3L.jpg,Filmfour,France|Germany|India|United Kingdom,2001-09-23,NaN,86.0,हिन्दी,Released,NaN,The Warrior,6.3,15.0
17229,NaN,NaN,Drama,25541.0,da,"Former Danish servicemen Lars and Jimmy are thrown together while training in a neo-Nazi group. Moving from hostility through grudging admiration to friendship and finally passion, events take a d...",2.587911,/q19Q5BRZpMXoNCA4OYodVozfjUh.jpg,,Sweden|Denmark,2009-10-21,NaN,90.0,Dansk,Released,NaN,Brotherhood,7.1,21.0
23044,NaN,NaN,Drama,25541.0,da,"Former Danish servicemen Lars and Jimmy are thrown together while training in a neo-Nazi group. Moving from hostility through grudging admiration to friendship and finally passion, events take a d...",2.587911,/q19Q5BRZpMXoNCA4OYodVozfjUh.jpg,,Sweden|Denmark,2009-10-21,NaN,90.0,Dansk,Released,NaN,Brotherhood,7.1,21.0
29374,NaN,NaN,Drama|Foreign,42495.0,en,"King Lear, old and tired, divides his kingdom among his daughters, giving great importance to their protestations of love for him. When Cordelia, youngest and most honest, refuses to idly flatter ...",0.187901,/xuE1IlUCohbxMY0fiqKTT6d013n.jpg,Royal Shakespeare Company|Laterna Film|Athena Film A/S,Denmark|United Kingdom,1971-02-04,NaN,137.0,English,Rumored,NaN,King Lear,8.0,3.0
15702,NaN,NaN,Drama|Foreign,42495.0,en,"King Lear, old and tired, divides his kingdom among his daughters, giving great importance to their protestations of love for him. When Cordelia, youngest and most honest, refuses to idly flatter ...",0.187901,/xuE1IlUCohbxMY0fiqKTT6d013n.jpg,Royal Shakespeare Company|Laterna Film|Athena Film A/S,Denmark|United Kingdom,1971-02-04,NaN,137.0,English,Rumored,NaN,King Lear,8.0,3.0
13946,NaN,NaN,Comedy,97995.0,en,"After breaking a mirror in his home, superstitious Max tries to avoid situations which could bring bad luck but in doing so, causes himself the worst luck imaginable.",0.141558,/4J6Ai4C5YRgfRUTlirrJ7QsmJKU.jpg,Max Linder Productions,United States of America,1921-02-06,NaN,62.0,English,Released,NaN,Seven Years Bad Luck,5.6,4.0
40276,NaN,NaN,Comedy,97995.0,en,"After breaking a mirror in his home, superstitious Max tries to avoid situations which could bring bad luck but in doing so, causes himself the worst luck imaginable.",0.141558,/4J6Ai4C5YRgfRUTlirrJ7QsmJKU.jpg,Max Linder Productions,United States of America,1921-02-06,NaN,62.0,English,Released,NaN,Seven Years Bad Luck,5.6,4.0
38871,NaN,NaN,Action|Drama|Romance|Adventure,99080.0,en,"Originally called White Thunder, American producer Varick Frissell's 1931 film was inspired by his love for the Canadian Arctic Circle. Set in a beautifully black-and-white filmed Newfoundland, it...",0.002362,/qenjwRvW9itR5pVp4CBkYfhVAOp.jpg,,,1931-06-21,NaN,70.0,English,Released,Actually produced during the Great Newfoundland Seal Hunt and You see the REAL thing,The Viking,NaN,0.0
16167,NaN,NaN,Action|Drama|Romance|Adventure,99080.0,en,"Originally called White Thunder, American producer Varick Frissell's 1931 film was inspired by his love for the Canadian Arctic Circle. Set in a beautifully black-and-white filmed Newfoundland, it...",0.002362,/qenjwRvW9itR5pVp4CBkYfhVAOp.jpg,,,1931-06-21,NaN,70.0,English,Released,Actually produced during the Great Newfoundland Seal Hunt and You see the REAL thing,The Viking,NaN,0.0
676,NaN,NaN,Drama|Romance,105045.0,de,"East-Berlin, 1961, shortly after the erection of the Wall. Konrad, Sophie and three of their friends plan a daring escape to Western Germany. The attempt is successful, except for Konrad, who rema...",0.122178,/5WFIrBhOOgc0jGmoLxMZwWqCctO.jpg,Studio Babelsberg|Centre National de la Cinématographie|Odessa Films|Canal+|Bioskop Film|Westdeutscher Rundfunk (WDR),Germany,1995-02-16,NaN,115.0,Deutsch,Released,"A love, a hope, a wall.",The Promise,5.0,1.0
1465,NaN,NaN,Drama|Romance,105045.0,de,"East-Berlin, 1961, shortly after the erection of the Wall. Konrad, Sophie and three of their friends plan a daring escape to Western Germany. The attempt is successful, except for Konrad, who rema...",0.122178,/5WFIrBhOOgc0jGmoLxMZwWqCctO.jpg,Studio Babelsberg|Centre National de la Cinématographie|Odessa Films|Canal+|Bioskop Film|Westdeutscher Rundfunk (WDR),Germany,1995-02-16,NaN,115.0,Deutsch,Released,"A love, a hope, a wall.",The Promise,5.0,1.0
19890,NaN,NaN,Fantasy|Drama|Science Fiction,119916.0,en,"Prospero, the true Duke of Milan is now living on an enchanted island with his daughter Miranda, the savage Caliban and Ariel, a spirit of the air. Raising a sorm to bring his brother - the usurpe...",0.000018,/gLVRTxaLtUDkfscFKPyYrCtRnTk.jpg,,,1980-02-27,NaN,123.0,,Released,NaN,The Tempest,NaN,0.0
21165,NaN,NaN,Fantasy|Drama|Science Fiction,119916.0,en,"Prospero, the true Duke of Milan is now living on an enchanted island with his daughter Miranda, the savage Caliban and Ariel, a spirit of the air. Raising a sorm to bring his brother - the usurpe...",0.000018,/gLVRTxaLtUDkfscFKPyYrCtRnTk.jpg,,,1980-02-27,NaN,123.0,,Released,NaN,The Tempest,NaN,0.0
13375,NaN,NaN,Thriller|Mystery,141971.0,fi,"Recovering from a nail gun shot to the head and 13 months of coma, doctor Pekka Valinta starts to unravel the mystery of his past, still suffering from total amnesia.",0.411949,/8VSZ9coCzxOCW2wE2Qene1H1fKO.jpg,Filmiteollisuus Fine,Finland,2008-12-26,NaN,108.0,suomi,Released,Which one is the first to return - memory or the murderer?,Blackout,6.7,3.0
13261,NaN,NaN,Thriller|Mystery,141971.0,fi,"Recovering from a nail gun shot to the head and 13 months of coma, doctor Pekka Valinta starts to unravel the mystery of his past, still suffering from total amnesia.",0.411949,/8VSZ9coCzxOCW2wE2Qene1H1fKO.jpg,Filmiteollisuus Fine,Finland,2008-12-26,NaN,108.0,suomi,Released,Which one is the first to return - memory or the murderer?,Blackout,6.7,3.0
16764,NaN,NaN,Thriller|Mystery,141971.0,fi,"Recovering from a nail gun shot to the head and 13 months of coma, doctor Pekka Valinta starts to unravel the mystery of his past, still suffering from total amnesia.",0.411949,/8VSZ9coCzxOCW2wE2Qene1H1fKO.jpg,Filmiteollisuus Fine,Finland,2008-12-26,NaN,108.0,suomi,Released,Which one is the first to return - memory or the murderer?,Blackout,6.7,3.0
19925,NaN,NaN,Drama|Science Fiction|Animation,152795.0,en,"More than two decades after catapulting to stardom with The Princess Bride, an aging actress (Robin Wright, playing a version of herself) decides to take her final job: preserving her digital like...",8.534039,/nnKX3ahYoT7P3au92dNgLf4pKwA.jpg,Pandora Filmproduktion|Entre Chien et Loup|Opus Film|Bridgit Folman Film Gang|Paul Thiltges Distributions|Liverpool,Belgium|France|Germany|Israel|Luxembourg|Poland,2013-05-16,0.045581,122.0,English,Released,NaN,The Congress,6.4,165.0
21854,NaN,NaN,Drama|Science Fiction|Animation,152795.0,en,"More than two decades after catapulting to stardom with The Princess Bride, an aging actress (Robin Wright, playing a version of herself) decides to take her final job: preserving her digital like...",8.534039,/nnKX3ahYoT7P3au92dNgLf4pKwA.jpg,Pandora Filmproduktion|Entre Chien et Loup|Opus Film|Bridgit Folman Film Gang|Paul Thiltges Distributions|Liverpool,Belgium|France|Germany|Israel|Luxembourg|Poland,2013-05-16,0.045581,122.0,English,Released,NaN,The Congress,6.4,165.0
13220,Why We Fight,NaN,Documentary,159849.0,en,"The third film of Frank Capra's 'Why We Fight"" propaganda film series, dealing with the Nazi conquest of Western Europe in 1940.",0.473322,/g21ruZZ3BZeUDuKMb82kejjtufk.jpg,,United States of America,1943-01-01,NaN,57.0,English,Released,NaN,Why We Fight: Divide and Conquer,5.0,1.0
35798,Why We Fight,NaN,Documentary,159849.0,en,"The third film of Frank Capra's 'Why We Fight"" propaganda film series, dealing with the Nazi conquest of Western Europe in 1940.",0.473322,/g21ruZZ3BZeUDuKMb82kejjtufk.jpg,,United States of America,1943-01-01,NaN,57.0,English,Released,NaN,Why We Fight: Divide and Conquer,5.0,1.0
13603,NaN,NaN,Drama|Comedy,168538.0,en,"In Zola's Paris, an ingenue arrives at a tony bordello: she's Nana, guileless, but quickly learning to use her erotic innocence to get what she wants. She's an actress for a soft-core filmmaker an...",1.276602,/pg4PUHRFrgNfACHSh5MITQ2gYch.jpg,Cannon Group|Metro-Goldwyn-Mayer (MGM),,1983-06-13,NaN,92.0,,Released,NaN,"Nana, the True Key of Pleasure",4.7,3.0
28860,NaN,NaN,Drama|Comedy,168538.0,en,"In Zola's Paris, an ingenue arrives at a tony bordello: she's Nana, guileless, but quickly learning to use her erotic innocence to get what she wants. She's an actress for a soft-core filmmaker an...",1.276602,/pg4PUHRFrgNfACHSh5MITQ2gYch.jpg,Cannon Group|Metro-Goldwyn-Mayer (MGM),,1983-06-13,NaN,92.0,,Released,NaN,"Nana, the True Key of Pleasure",4.7,3.0
24164,NaN,NaN,Comedy|Drama,265189.0,sv,"While holidaying in the French Alps, a Swedish family deals with acts of cowardliness as an avalanche breaks out.",12.165685,/rGMtc9AtZsnWSSL5VnLaGvx1PI6.jpg,Motlys|Coproduction Office|Film i Väst,Norway|Sweden|France,2014-08-15,0.135950,118.0,Français|Norsk|svenska|English,Released,NaN,Force Majeure,6.8,255.0
45265,NaN,NaN,Comedy|Drama,265189.0,sv,"While holidaying in the French Alps, a Swedish family deals with acts of cowardliness as an avalanche breaks out.",12.165685,/rGMtc9AtZsnWSSL5VnLaGvx1PI6.jpg,Motlys|Coproduction Office|Film i Väst,Norway|Sweden|France,2014-08-15,0.135950,118.0,Français|Norsk|svenska|English,Released,NaN,Force Majeure,6.8,255.0
33184,NaN,0.098,Drama|Fantasy,298721.0,th,"In a hospital, ten soldiers are being treated for a mysterious sleeping sickness. In a story in which dreams can be experienced by others, and in which goddesses can sit casually with mortals, a n...",2.535419,/5GasjPRAy5rlEyDOH7MeOyxyQGX.jpg,"Match Factory, The|Louverture Films|Tordenfilm AS|ZDF/Arte|Geißendörfer Film- und Fernsehproduktion (GFF)|Illumination Films|Detalle Films|Centre National de la Cinématographie (CNC)|Astro Shaw|Ki...",United Kingdom|United States of America|France|Thailand|Germany|Malaysia|South Korea|Mexico|Norway,2015-09-02,NaN,122.0,English|ภาษาไทย,Released,NaN,Cemetery of Splendour,4.4,50.0
40040,NaN,0.098,Drama|Fantasy,298721.0,th,"In a hospital, ten soldiers are being treated for a mysterious sleeping sickness. In a story in which dreams can be experienced by others, and in which goddesses can sit casually with mortals, a n...",2.535419,/5GasjPRAy5rlEyDOH7MeOyxyQGX.jpg,"Match Factory, The|Louverture Films|Tordenfilm AS|ZDF/Arte|Geißendörfer Film- und Fernsehproduktion (GFF)|Illumination Films|Detalle Films|Centre National de la Cinématographie (CNC)|Astro Shaw|Ki...",United Kingdom|United States of America|France|Thailand|Germany|Malaysia|South Korea|Mexico|Norway,2015-09-02,NaN,122.0,English|ภาษาไทย,Released,NaN,Cemetery of Splendour,4.4,50.0

In [854]:
movies.drop_duplicates(inplace = True)

In [855]:
movies[movies.duplicated(subset = "id" , keep = False)].sort_values(by = "id")

,belongs_to_collection,budget,genres,id,original_language,overview,popularity,poster_path,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
33826,NaN,3.000000e+00,Comedy|Crime|Drama|Romance|Thriller,4912.0,en,"Television made him famous, but his biggest hits happened off screen. Television producer by day, CIA assassin by night, Chuck Barris was recruited by the CIA at the height of his TV career and tr...",7.645827,/o3Im9nPLAgtlw1j2LtpMebAotSe.jpg,Miramax Films|Allied Filmmakers|Mad Chance,United States of America,2002-12-30,3.301381,113.0,English,Released,Some things are better left top secret.,Confessions of a Dangerous Mind,6.6,281.0
5865,NaN,3.000000e+00,Comedy|Crime|Drama|Romance|Thriller,4912.0,en,"Television made him famous, but his biggest hits happened off screen. Television producer by day, CIA assassin by night, Chuck Barris was recruited by the CIA at the height of his TV career and tr...",11.331072,/o3Im9nPLAgtlw1j2LtpMebAotSe.jpg,Miramax Films|Allied Filmmakers|Mad Chance,United States of America,2002-12-30,3.301381,113.0,English,Released,Some things are better left top secret.,Confessions of a Dangerous Mind,6.6,281.0
4114,Pokémon Collection,1.600000e+00,Adventure|Fantasy|Animation|Action|Family,10991.0,ja,"When Molly Hale's sadness of her father's disappearance get to her, she unknowingly uses the Unown to create her own dream world along with Entei, who she believes to be her father. When Entei kid...",10.264597,/5ILjS6XB5deiHop8SXPsYxXWVPE.jpg,TV Tokyo|4 Kids Entertainment|Nintendo|Pikachu Project|Oriental Light and Magic (OLM)|Kids' WB|Pikachu Project 2001|Shoakuken,Japan,2000-07-08,6.841127,93.0,English,Released,Pokémon: Spell of the Unknown,Pokémon: Spell of the Unknown,6.0,143.0
44821,Pokémon Collection,1.600000e+00,Adventure|Fantasy|Animation|Action|Family,10991.0,ja,"When Molly Hale's sadness of her father's disappearance get to her, she unknowingly uses the Unown to create her own dream world along with Entei, who she believes to be her father. When Entei kid...",6.480376,/5ILjS6XB5deiHop8SXPsYxXWVPE.jpg,TV Tokyo|4 Kids Entertainment|Nintendo|Pikachu Project|Oriental Light and Magic (OLM)|Kids' WB|Pikachu Project 2001|Shoakuken,Japan,2000-07-08,6.841127,93.0,English,Released,Pokémon: Spell of the Unknown,Pokémon: Spell of the Unknown,6.0,144.0
44826,Pokémon Collection,NaN,Adventure|Fantasy|Animation|Science Fiction|Family,12600.0,ja,"All your favorite Pokémon characters are back, and are joined for the first time by the legendary Pokémon Celebi and Suicune, in this latest exciting Pokémon adventure! In order to escape a greedy...",6.080108,/bqL0PVHbQ8Jmw3Njcl38kW0CoeM.jpg,,Japan|United States of America,2001-07-06,2.802356,75.0,日本語,Released,NaN,Pokémon 4Ever: Celebi - Voice of the Forest,5.7,82.0
5535,Pokémon Collection,NaN,Adventure|Fantasy|Animation|Science Fiction|Family,12600.0,ja,"All your favorite Pokémon characters are back, and are joined for the first time by the legendary Pokémon Celebi and Suicune, in this latest exciting Pokémon adventure! In order to escape a greedy...",7.072301,/bqL0PVHbQ8Jmw3Njcl38kW0CoeM.jpg,,Japan|United States of America,2001-07-06,2.802356,75.0,日本語,Released,NaN,Pokémon 4Ever: Celebi - Voice of the Forest,5.7,82.0
15765,NaN,2.500000e-04,Drama|Comedy|Foreign,13209.0,fa,"Since women are banned from soccer matches, Iranian females masquerade as males so they can slip into Tehran's stadium to see the game between Iran and Bahrain. The ones who are caught and arreste...",1.529879,/nfkOkpudNNIjRrf0mTFVoiGzHyc.jpg,Jafar Panahi Film Productions,Iran,2006-05-26,NaN,93.0,فارسی,Released,NaN,Offside,6.7,27.0
11342,NaN,2.500000e-04,Drama|Comedy|Foreign,13209.0,fa,"Since women are banned from soccer matches, Iranian females masquerade as males so they can slip into Tehran's stadium to see the game between Iran and Bahrain. The ones who are caught and arreste...",1.528960,/nfkOkpudNNIjRrf0mTFVoiGzHyc.jpg,Jafar Panahi Film Productions,Iran,2006-05-26,NaN,93.0,فارسی,Released,NaN,Offside,6.7,27.0
10419,NaN,1.600000e-01,Drama|Crime|Mystery,14788.0,en,"Set against the backdrop of a decaying Midwestern town, a murder becomes the focal point of three people who work in a doll factory.",3.185256,/w56oo9nREcF54sNXVYuE9QxZFjT.jpg,Magnolia Pictures|Extension 765,United States of America,2005-09-03,NaN,73.0,English,Released,NaN,Bubble,6.4,36.0
12066,NaN,1.600000e-01,Drama|Crime|Mystery,14788.0,en,"Set against the backdrop of a decaying Midwestern town, a murder becomes the focal point of three people who work in a doll factory.",3.008299,/w56oo9nREcF54sNXVYuE9QxZFjT.jpg,Magnolia Pictures|Extension 765,United States of America,2005-09-03,NaN,73.0,English,Released,NaN,Bubble,6.4,36.0
5130,NaN,2.600000e+00,Adventure|Family|Science Fiction|Thriller,15028.0,en,"Until now, Zak Gibbs' greatest challenge has been to find a way to buy a car. But when he discovers an odd wristwatch amidst his father's various inventions and slips it on -- something very stran...",5.373623,/xGhDPrBz9mJN8CsIjA23jQSd3sc.jpg,Paramount Pictures|Nickelodeon Movies|Valhalla Motion Pictures,United States of America,2002-03-17,3.879328,94.0,Český|English,Released,"The adventure of a lifetime, in a few mere seconds.",Clockstoppers,4.9,89.0
33743,NaN,2.600000e+00,Adventure|Family|Science Fiction|Thriller,15028.0,en,"Until now, Zak Gibbs' greatest challenge has been to find a way to buy a car. But when he discovers an odd wristwatch amidst his father's various inventions and slips it on -- something very stran...",4.920175,/xGhDPrBz9mJN8CsIjA23jQSd3sc.jpg,Paramount Pictures|Nickelodeon Movies|Valhalla Motion Pictures,United States of America,2002-03-17,3.879328,94.0,Český|English,Released,"The adventure of a lifetime, in a few mere seconds.",Clockstoppers,4.9,90.0
949,NaN,4.000000e-07,Drama|Romance|War,22649.0,en,"British nurse Catherine Barkley (Helen Hayes) and American Lieutenant Frederic Henry (Gary Cooper) fall in love during the First World War in Italy. Eventually separated by Frederic's transfer, tr...",1.914697,/k0MF0IIbJ2PfOIku2KyraXL72d8.jpg,Paramount Pictures,United States of America,1932-12-08,0.000003,89.0,English,Released,Every woman who has loved will understand,A Farewell to Arms,6.2,29.0
15074,NaN,4.000000e-07,Drama|Romance|War,22649.0,en,"British nurse Catherine Barkley (Helen Hayes) and American Lieutenant Frederic Henry (Gary Cooper) fall in love during the First World War in Italy. Eventually separated by Frederic's transfer, tr...",2.411191,/k0MF0IIbJ2PfOIku2KyraXL72d8.jpg,Paramount Pictures,United States of America,1932-12-08,0.000003,89.0,English,Released,Every woman who has loved will understand,A Farewell to Arms,6.2,29.0
9576,NaN,1.000000e+00,Drama|Horror|Music|Romance|TV Movie,69234.0,en,"Count de Chagnie has discovered Christine's singing talent on a market place and sent her to his friend Carriere, the director of the Parisian opera. However just when she arrives Carriere's dismi...",0.441872,/ole8e9YQwvHoKVpWO0lgfLFFemc.jpg,Beta Film|Reteitalia|TF1|Hexatel|Saban/Scherick Productions|Saban International N.V.|StarCom,France|Germany|Italy|United States of America,1990-03-18,NaN,168.0,English|Italiano,Released,NaN,The Phantom of the Opera,5.0,3.0
26625,NaN,1.000000e+00,Drama|Horror|Music|Romance|TV Movie,69234.0,en,"Count de Chagnie has discovered Christine's singing talent on a market place and sent her to his friend Carriere, the director of the Parisian opera. However just when she arrives Carriere's dismi...",0.438490,/ole8e9YQwvHoKVpWO0lgfLFFemc.jpg,Beta Film|Reteitalia|TF1|Hexatel|Saban/Scherick Productions|Saban International N.V.|StarCom,France|Germany|Italy|United States of America,1990-03-18,NaN,168.0,English|Italiano,Released,NaN,The Phantom of the Opera,5.0,3.0
20843,NaN,4.000000e+00,Adventure|Drama,77221.0,en,"On the Arabian Peninsula in the 1930s, two warring leaders come face to face. The victorious Nesib, Emir of Hobeika, lays down his peace terms to rival Amar, Sultan of Salmaah. The two men agree t...",6.475665,/iQd7zWhSeCe3cgdPcLIDXjGfdzL.jpg,"France 2 Cinéma|Quinta Communications|Carthago Films S.a.r.l.|Prima TV|Doha Film Institute, The",France|Italy|Qatar|Tunisia,2011-12-21,0.544600,130.0,English,Released,NaN,Black Gold,5.9,77.0
11155,NaN,4.000000e+00,Adventure|Drama,77221.0,en,"On the Arabian Peninsula in the 1930s, two warring leaders come face to face. The victorious Nesib, Emir of Hobeika, lays down his peace terms to rival Amar, Sultan of Salmaah. The two men agree t...",6.652197,/iQd7zWhSeCe3cgdPcLIDXjGfdzL.jpg,"France 2 Cinéma|Quinta Communications|Carthago Films S.a.r.l.|Prima TV|Doha Film Institute, The",France|Italy|Qatar|Tunisia,2011-12-21,0.544600,130.0,English,Released,NaN,Black Gold,5.9,77.0
21116,NaN,NaN,Documentary,84198.0,en,"Using personal stories, this powerful documentary illuminates the plight of the 49 million Americans struggling with food insecurity. A single mother, a small-town policeman and a farmer are among...",1.673307,/jn8L1QdWWX5c0NUOLjzaSXtZrbt.jpg,,United States of America,2012-03-22,NaN,84.0,English,Released,One Nation. Underfed.,A Place at the Table,6.9,7.0
2564,NaN,NaN,Documentary,84198.0,en,"Using personal stories, this powerful documentary illuminates the plight of the 49 million Americans struggling with food insecurity. A single mother, a small-town policeman and a farmer are among...",0.501046,/jn8L1QdWWX5c0NUOLjzaSXtZrbt.jpg,,United States of America,2012-03-22,NaN,84.0,English,Released,One Nation. Underfed.,A Place at the Table,6.9,7.0
20899,NaN,NaN,Drama,109962.0,en,"Two literary women compete for 20 years: one writes for the critics; the other one, to get rich.",10.396878,/tOflyY8eUFWubLKJH7fKg4KwpCl.jpg,Metro-Goldwyn-Mayer (MGM)|Jaquet,United States of America,1981-09-23,NaN,115.0,English,Released,"From the very beginning, they knew they'd be friends to the end. What they didn't count on was everything in between.",Rich and Famous,4.9,7.0
5710,NaN,NaN,Drama,109962.0,en,"Two literary women compete for 20 years: one writes for the critics; the other one, to get rich.",12.180836,/tOflyY8eUFWubLKJH7fKg4KwpCl.jpg,Metro-Goldwyn-Mayer (MGM)|Jaquet,United States of America,1981-09-23,NaN,115.0,English,Released,"From the very beginning, they knew they'd be friends to the end. What they didn't count on was everything in between.",Rich and Famous,4.9,7.0
23534,NaN,3.512454e-01,Drama,110428.0,fr,"Winter, 1915. Confined by her family to an asylum in the South of France - where she will never sculpt again - the chronicle of Camille Claudel's reclusive life, as she waits for a visit from her ...",0.110065,/sGMPDg6je1zKi0TiX9b4pP6yN02.jpg,Canal+|Arte France Cinéma|3B Productions|C.R.R.A.V. Nord Pas de Calais|Region PACA,France,2013-03-13,0.011586,95.0,Français,Released,NaN,Camille Claudel 1915,7.0,20.0
4356,NaN,3.512454e-01,Drama,110428.0,fr,"Winter, 1915. Confined by her family to an asylum in the South of France - where she will never sculpt again - the chronicle of Camille Claudel's reclusive life, as she waits for a visit from her ...",0.134014,/sGMPDg6je1zKi0TiX9b4pP6yN02.jpg,Canal+|Arte France Cinéma|3B Productions|C.R.R.A.V. Nord Pas de Calais|Region PACA,France,2013-03-13,0.011586,95.0,Français,Released,NaN,Camille Claudel 1915,7.0,20.0
30001,NaN,NaN,Drama,132641.0,ja,"Ten years into a marriage, the wife is disappointed by the husband's lack of financial success, meaning she has to work and can't treat herself and the husband finds the wife slovenly and mean-spi...",0.619388,/z9WiHt5uQjs8L8tyBpRBKzlheF2.jpg,Toho Company,Japan,1953-04-29,NaN,89.0,日本語,Released,NaN,Wife,NaN,0.0
838,NaN,NaN,Drama,132641.0,ja,"Ten years into a marriage, the wife is disappointed by the husband's lack of financial success, meaning she has to work and can't treat herself and the husband finds the wife slovenly and mean-spi...",0.096079,/z9WiHt5uQjs8L8tyBpRBKzlheF2.jpg,Toho Company,Japan,1953-04-29,NaN,89.0,日本語,Released,NaN,Wife,NaN,0.0
19730,NaN,NaN,Carousel Productions|Vision View Entertainment|Telescene Film Group Productions,NaN,104.0,Released,NaN,Midnight Man,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29503,NaN,NaN,Aniplex|GoHands|BROSTA TV|Mardock Scramble Production Committee|Sentai Filmworks,NaN,68.0,Released,NaN,Mardock Scramble: The Third Exhaust,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35587,NaN,NaN,Odyssey Media|Pulser Productions|Rogue State|The Cartel,NaN,82.0,Released,NaN,Avalanche Sharks,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [856]:
movies.drop_duplicates(subset = "id", inplace = True)

In [857]:
movies.id.value_counts(dropna = True)

id
862.0       1
40777.0     1
107308.0    1
16247.0     1
99904.0     1
           ..
44399.0     1
10138.0     1
32084.0     1
42191.0     1
461257.0    1
Name: count, Length: 45433, dtype: int64

## Handling Missing Values & Removing Observations

17. __Drop__ all rows/movies with unknown __id__ or __title__.

In [858]:
movies.isna().sum()

belongs_to_collection    40946
budget                   36554
genres                    2442
id                           1
original_language           11
overview                   954
popularity                   4
poster_path                386
production_companies         4
production_countries         4
release_date                88
revenue                  38036
runtime                   1819
spoken_languages             4
status                      85
tagline                  25037
title                        4
vote_average              2900
vote_count                   4
dtype: int64

In [859]:
movies.dropna(subset = ["title","id"],inplace = True)
movies.id = movies.id.astype("int")

18. __Keep__ only those rows/movies in the df with __10 or more non-NaN__ values.

In [860]:
movies.notna().sum(axis = 1)

0        18
1        18
2        17
3        18
4        18
         ..
45461    15
45462    15
45463    16
45464    13
45465    13
Length: 45430, dtype: int64

In [861]:
movies[movies.notna().sum(axis=1)  ==  9]

,belongs_to_collection,budget,genres,id,original_language,overview,popularity,poster_path,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
18038,NaN,NaN,NaN,344741,pl,NaN,0.000000,NaN,,,NaT,NaN,NaN,,Released,NaN,Pajęczarki,NaN,0.0
20166,NaN,NaN,NaN,139909,fi,NaN,0.000127,NaN,,,NaT,NaN,NaN,,Released,NaN,Aurinkotuuli,NaN,0.0
41718,NaN,NaN,NaN,216550,de,NaN,0.000000,NaN,,,NaT,NaN,NaN,,Released,NaN,Dolpo Tulku - Heimkehr in den Himalaya,NaN,0.0
44978,NaN,NaN,NaN,398295,pt,NaN,0.000331,NaN,,,NaT,NaN,NaN,,Released,NaN,Mundo Cão,NaN,0.0

In [862]:
movies.dropna(thresh = 10,inplace = True)

## Final (Cleaning) Steps

19. __Keep__ only those rows/movies in the df with __status "Released"__. Then __drop__ the column "status".

In [863]:
movies.status.value_counts()

status
Released           44981
Rumored              229
Post Production       98
In Production         20
Planned               15
Canceled               2
Name: count, dtype: int64

In [864]:
movies = movies.loc[movies.status == "Released"].copy()

In [865]:
movies.drop(columns = ["status"] , inplace = True)

20. The Order of the columns should be as follows:

In [884]:
col = ["id", "title", "tagline", "release_date", "genres", "belongs_to_collection", 
"original_language", "budget_musd", "revenue_musd", "production_companies",
"production_countries", "vote_count", "vote_average", "popularity", "runtime",
"overview", "spoken_languages", "poster_path"]

In [888]:
movies.rename(columns={"revenue": "revenue_musd"}, inplace=True)
movies.rename(columns={"budget": "budget_musd"}, inplace=True)
movies = movies.loc[:,col]

21. __Reset__ the Index and create a __RangeIndex__.

In [894]:
movies.reset_index(drop = True,inplace = False)

,id,title,tagline,release_date,genres,belongs_to_collection,original_language,budget_musd,revenue_musd,production_companies,production_countries,vote_count,vote_average,popularity,runtime,overview,spoken_languages,poster_path
0,862,Toy Story,NaN,1995-10-30,Animation|Comedy|Family,Toy Story Collection,en,3.0,37.355403,Pixar Animation Studios,United States of America,5415.0,7.7,21.946943,81.0,"Led by Woody, Andy's toys live happily in his room until Andy's birthday brings Buzz Lightyear onto the scene. Afraid of losing his place in Andy's heart, Woody plots against Buzz. But when circum...",English,/rhIRbceoE9lR4veEXuwCC2wARtG.jpg
1,8844,Jumanji,Roll the dice and unleash the excitement!,1995-12-15,Adventure|Fantasy|Family,NaN,en,6.5,26.279725,TriStar Pictures|Teitler Film|Interscope Communications,United States of America,2413.0,6.9,17.015539,104.0,"When siblings Judy and Peter discover an enchanted board game that opens the door to a magical world, they unwittingly invite Alan -- an adult who's been trapped inside the game for 26 years -- in...",English|Français,/vzmL6fP7aPKNKPRTFnZmiUfciyV.jpg
2,15602,Grumpier Old Men,Still Yelling. Still Fighting. Still Ready for Love.,1995-12-22,Romance|Comedy,Grumpy Old Men Collection,en,NaN,NaN,Warner Bros.|Lancaster Gate,United States of America,92.0,6.5,11.712900,101.0,"A family wedding reignites the ancient feud between next-door neighbors and fishing buddies John and Max. Meanwhile, a sultry Italian divorcée opens a restaurant at the local bait shop, alarming t...",English,/6ksm1sjKMFLbO7UY2i6G1ju9SML.jpg
3,31357,Waiting to Exhale,Friends are the people who let you be yourself... and never let you forget it.,1995-12-22,Comedy|Drama|Romance,NaN,en,1.6,8.145216,Twentieth Century Fox Film Corporation,United States of America,34.0,6.1,3.859495,127.0,"Cheated on, mistreated and stepped on, the women are holding their breath, waiting for the elusive ""good man"" to break a string of less-than-stellar lovers. Friends and confidants Vannah, Bernie, ...",English,/16XOMpEaLWkrcPqSQqhTmeJuqQl.jpg
4,11862,Father of the Bride Part II,Just When His World Is Back To Normal... He's In For The Surprise Of His Life!,1995-02-10,Comedy,Father of the Bride Collection,en,NaN,7.657891,Sandollar Productions|Touchstone Pictures,United States of America,173.0,5.7,8.387519,106.0,"Just when George Banks has recovered from his daughter's wedding, he receives the news that she's pregnant ... and that George's wife, Nina, is expecting too. He was planning on selling their home...",English,/e64sOI48hQXyru7naBFyssKFxVd.jpg
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44976,439050,Subdue,Rising and falling between a man and woman,NaT,Drama|Family,NaN,fa,NaN,NaN,,Iran,1.0,4.0,0.072051,90.0,Rising and falling between a man and woman.,فارسی,/jldsYflnId4tTWPx8es3uzsB1I8.jpg
44977,111109,Century of Birthing,NaN,2011-11-17,Drama,NaN,tl,NaN,NaN,Sine Olivia,Philippines,3.0,9.0,0.178241,360.0,An artist struggles to finish his work while a storyline about a cult plays in his head.,,/xZkmxsNmYXJbKVsTRLLx3pqGHx7.jpg
44978,67758,Betrayal,A deadly game of wits.,2003-08-01,Action|Drama|Thriller,NaN,en,NaN,NaN,American World Pictures,United States of America,6.0,3.8,0.903007,90.0,"When one of her hits goes wrong, a professional assassin ends up with a suitcase full of a million dollars belonging to a mob boss ...",English,/d5bX92nDsISNhu3ZT69uHwmfCGw.jpg
44979,227506,Satan Triumphant,NaN,1917-10-21,NaN,NaN,en,NaN,NaN,Yermoliev,Russia,0.0,NaN,0.003503,87.0,"In a small town live two brothers, one a minister and the other one a hunchback painter of the chapel who lives with his wife. One dreadful and stormy night, a stranger knocks at the door asking f...",,/aorBPO7ak8e8iJKT5OcqYxU3jlK.jpg
44980,461257,Queerama,NaN,2017-06-09,NaN,NaN,en,NaN,NaN,,United Kingdom,0.0,NaN,0.163015,75.0,"50 years after decriminalisation of homosexuality in the UK, director Daisy Asquith mines the jewels of the BFI archive to take us into the relationships, desires, fears and expressions of gay men...",English,/s5UkZt6NTsrS7ZF0Rh8nzupRlIU.jpg

In [895]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44981 entries, 0 to 44980
Data columns (total 18 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     44981 non-null  int32
 1   title                  44981 non-null  object
 2   tagline                20285 non-null  object
 3   release_date           44907 non-null  datetime64[ns]
 4   genres                 42601 non-null  object
 5   belongs_to_collection  4463 non-null   object
 6   original_language      44971 non-null  object
 7   budget_musd            8855 non-null   float64
 8   revenue_musd           7385 non-null   float64
 9   production_companies   44981 non-null  object
 10  production_countries   44981 non-null  object
 11  vote_count             44981 non-null  float64
 12  vote_average           42145 non-null  float64
 13  popularity             44981 non-null  float64
 14  runtime                43238 non-null  float64
 15  overview               44065 non-null  object
 16  spoken_languages       44981 non-null  object
 17  poster_path            44612 non-null  object
dtypes: datetime64[ns](1), float64(6), int32(1), object(10)
memory usage: 6.0+ MB

22. __Save__ the cleaned dataset in a __csv-file__.

In [902]:
movies.to_csv("Cleaned_movies.csv" , index = False)

In [903]:
df = pd.read_csv("Cleaned_movies.csv")

# +++++++++ See some Hints below +++++++++++++

In [904]:
df

,id,title,tagline,release_date,genres,belongs_to_collection,original_language,budget_musd,revenue_musd,production_companies,production_countries,vote_count,vote_average,popularity,runtime,overview,spoken_languages,poster_path
0,862,Toy Story,NaN,1995-10-30,Animation|Comedy|Family,Toy Story Collection,en,3.0,37.355403,Pixar Animation Studios,United States of America,5415.0,7.7,21.946943,81.0,"Led by Woody, Andy's toys live happily in his room until Andy's birthday brings Buzz Lightyear onto the scene. Afraid of losing his place in Andy's heart, Woody plots against Buzz. But when circum...",English,/rhIRbceoE9lR4veEXuwCC2wARtG.jpg
1,8844,Jumanji,Roll the dice and unleash the excitement!,1995-12-15,Adventure|Fantasy|Family,NaN,en,6.5,26.279725,TriStar Pictures|Teitler Film|Interscope Communications,United States of America,2413.0,6.9,17.015539,104.0,"When siblings Judy and Peter discover an enchanted board game that opens the door to a magical world, they unwittingly invite Alan -- an adult who's been trapped inside the game for 26 years -- in...",English|Français,/vzmL6fP7aPKNKPRTFnZmiUfciyV.jpg
2,15602,Grumpier Old Men,Still Yelling. Still Fighting. Still Ready for Love.,1995-12-22,Romance|Comedy,Grumpy Old Men Collection,en,NaN,NaN,Warner Bros.|Lancaster Gate,United States of America,92.0,6.5,11.712900,101.0,"A family wedding reignites the ancient feud between next-door neighbors and fishing buddies John and Max. Meanwhile, a sultry Italian divorcée opens a restaurant at the local bait shop, alarming t...",English,/6ksm1sjKMFLbO7UY2i6G1ju9SML.jpg
3,31357,Waiting to Exhale,Friends are the people who let you be yourself... and never let you forget it.,1995-12-22,Comedy|Drama|Romance,NaN,en,1.6,8.145216,Twentieth Century Fox Film Corporation,United States of America,34.0,6.1,3.859495,127.0,"Cheated on, mistreated and stepped on, the women are holding their breath, waiting for the elusive ""good man"" to break a string of less-than-stellar lovers. Friends and confidants Vannah, Bernie, ...",English,/16XOMpEaLWkrcPqSQqhTmeJuqQl.jpg
4,11862,Father of the Bride Part II,Just When His World Is Back To Normal... He's In For The Surprise Of His Life!,1995-02-10,Comedy,Father of the Bride Collection,en,NaN,7.657891,Sandollar Productions|Touchstone Pictures,United States of America,173.0,5.7,8.387519,106.0,"Just when George Banks has recovered from his daughter's wedding, he receives the news that she's pregnant ... and that George's wife, Nina, is expecting too. He was planning on selling their home...",English,/e64sOI48hQXyru7naBFyssKFxVd.jpg
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44976,439050,Subdue,Rising and falling between a man and woman,NaN,Drama|Family,NaN,fa,NaN,NaN,NaN,Iran,1.0,4.0,0.072051,90.0,Rising and falling between a man and woman.,فارسی,/jldsYflnId4tTWPx8es3uzsB1I8.jpg
44977,111109,Century of Birthing,NaN,2011-11-17,Drama,NaN,tl,NaN,NaN,Sine Olivia,Philippines,3.0,9.0,0.178241,360.0,An artist struggles to finish his work while a storyline about a cult plays in his head.,NaN,/xZkmxsNmYXJbKVsTRLLx3pqGHx7.jpg
44978,67758,Betrayal,A deadly game of wits.,2003-08-01,Action|Drama|Thriller,NaN,en,NaN,NaN,American World Pictures,United States of America,6.0,3.8,0.903007,90.0,"When one of her hits goes wrong, a professional assassin ends up with a suitcase full of a million dollars belonging to a mob boss ...",English,/d5bX92nDsISNhu3ZT69uHwmfCGw.jpg
44979,227506,Satan Triumphant,NaN,1917-10-21,NaN,NaN,en,NaN,NaN,Yermoliev,Russia,0.0,NaN,0.003503,87.0,"In a small town live two brothers, one a minister and the other one a hunchback painter of the chapel who lives with his wife. One dreadful and stormy night, a stranger knocks at the door asking f...",NaN,/aorBPO7ak8e8iJKT5OcqYxU3jlK.jpg
44980,461257,Queerama,NaN,2017-06-09,NaN,NaN,en,NaN,NaN,NaN,United Kingdom,0.0,NaN,0.163015,75.0,"50 years after decriminalisation of homosexuality in the UK, director Daisy Asquith mines the jewels of the BFI archive to take us into the relationships, desires, fears and expressions of gay men...",English,/s5UkZt6NTsrS7ZF0Rh8nzupRlIU.jpg

# ++++++++++++++++ Hints++++++++++++++++++++

__Hints for 3.__ <br>
apply ast.literal_eval() on all stringified elements (you have to import ast):

In [ ]:
# example:
df.stringified_column = df.stringified_column.apply(lambda x: ast.literal_eval(x) if isinstance(x, str) else np.nan)

__Hints for 4., 5., 6., 7., 8.__<br> 
apply an appropriate lambda function on all column elements

__Hints for 9.__<br>
Replace all __""__ (empty strings) in the above columns by NaN (__np.nan__)

__Hints for 10.__<br>
Use pd.to_numeric() and "coerce" errors

__Hints for 11.__<br>
Replace the value 0 by NaN (__np.nan__)

__Hints for 13.__<br>
Replace the value 0 by NaN (__np.nan__)

__Hints for 14.__<br>
Use pd.to_datetime() and "coerce" errors

__Hints for 16.__<br>
There cannot be two or more movies with the same movie id.